description: Asynchronous management events configuration
type: object
x-examples:
  example-1:
    errors:
      cpu:
        threshold: 90
        reportIntervalInSec: 1800
      flash:
        threshold: 90
        reportIntervalInSec: 1800
      ram:
        threshold: 90
        reportIntervalInSec: 1800
      reader_gateway: true
      antenna: false
      database: true
      radio: true
      radio_control: true
    warnings:
      cpu:
        threshold: 80
        reportIntervalInSec: 1800
      flash:
        threshold: 80
        reportIntervalInSec: 1800
      ram:
        threshold: 80
        reportIntervalInSec: 1800
      ntp:
        threshold: 0
        reportIntervalInSec: 1800
      database: true
      radio_api: true
      radio_control: true
      temperature:
        ambient: 75
        pa: 105
    gpiEvents: true
    userappEvents: true
    heartbeat:
      fields:
        radio_control:
        - ANTENNAS
        - RADIO_ACTIVITY
        - RADIO_CONNECTION
        - CPU
        - RAM
        - UPTIME
        - NUM_ERRORS
        - NUM_WARNINGS
        - NUM_TAG_READS
        - NUM_TAG_READS_PER_ANTENNA
        - NUM_DATA_MESSAGES_TXED
        - NUM_RADIO_PACKETS_RXED
        reader_gateway:
        - NUM_DATA_MESSAGES_RXED
        - NUM_DATA_MESSAGES_TXED
        - NUM_DATA_MESSAGES_RETAINED
        - NUM_DATA_MESSAGES_DROPPED
        - NUM_MANAGEMENT_EVENTS_TXED
        - CPU
        - RAM
        - UPTIME
        - NUM_ERRORS
        - NUM_WARNINGS
        system:
        - CPU
        - FLASH
        - NTP
        - RAM
        - SYSTEMTIME
        - TEMPERATURE
        - UPTIME
        userapps:
        - STATUS
        - CPU
        - RAM
        - UPTIME
        - NUM_DATA_MESSAGES_RXED
        - NUM_DATA_MESSAGES_TXED
        - INCOMING_DATA_BUFFER_PERCENTAGE_REMAINING
        - OUTGOING_DATA_BUFFER_PERCENTAGE_REMAINING
      interval: 60
title: Management Events Configuration
properties:
  errors:
    type: object
    description: Asynchronous Management Errors
    properties:
      cpu:
        type: object
        description: CPU Usage Error Alerts
        properties:
          threshold:
            type: number
            description: Error CPU usage limit
            default: 90
            example: 90
            minimum: 1
            maximum: 99
          reportIntervalInSec:
            type: number
            default: 1800
            example: 1800
            minimum: 1
            description: Error Report Interval in seconds.
        required:
        - threshold
      flash:
        type: object
        description: Flash Usage Error Alerts
        properties:
          threshold:
            type: number
            description: Error FLASH usage limit
            default: 90
            example: 90
            minimum: 1
            maximum: 99
          reportIntervalInSec:
            type: number
            description: Error Report Interval in seconds.
            default: 1800
            example: 1800
            minimum: 1
        required:
        - threshold
      ram:
        type: object
        description: RAM Usage Error Alerts
        properties:
          threshold:
            type: number
            description: Error RAM usage limit
            default: 90
            example: 90
            minimum: 1
            maximum: 99
          reportIntervalInSec:
            type: number
            description: Error Report Interval in seconds.
            default: 1800
            minimum: 1
            example: 1800
        required:
        - threshold
      reader_gateway:
        type: boolean
        default: true
        description: Reader Gateway Errors
      antenna:
        type: boolean
        description: Antenna Connect/Disconnect Alerts
        default: true
      database:
        type: boolean
        default: true
        description: Radio Database Error Alerts
      radio:
        type: boolean
        default: true
        description: Radio Error Alerts
      radio_control:
        type: boolean
        default: true
        description: Radio Control Error Alerts
  warnings:
    type: object
    description: Asynchronous Management Warnings
    properties:
      cpu:
        type: object
        description: CPU Usage Warning Alerts
        properties:
          threshold:
            type: number
            description: Warning CPU usage limit
            default: 80
            example: 80
            minimum: 1
            maximum: 99
          reportIntervalInSec:
            type: number
            default: 1800
            example: 1800
            minimum: 1
            description: Warning Report Interval in seconds.
        required:
        - threshold
      flash:
        type: object
        description: Flash Usage Warning Alerts
        properties:
          threshold:
            type: number
            description: Warning FLASH usage limit
            default: 80
            example: 90
            minimum: 1
            maximum: 99
          reportIntervalInSec:
            type: number
            description: Warning Report Interval in seconds.
            default: 1800
            example: 1800
            minimum: 1
        required:
        - threshold
      ram:
        type: object
        description: RAM Usage Warning Alerts
        properties:
          threshold:
            type: number
            description: Warning RAM usage limit
            default: 90
            example: 90
            minimum: 1
            maximum: 99
          reportIntervalInSec:
            type: number
            description: Warning Report Interval in seconds.
            default: 1800
            minimum: 1
            example: 1800
        required:
        - threshold
      ntp:
        description: NTP Warning Alert
        oneOf:
        - type: object
          description: NTP offset warnings config
          properties:
            threshold:
              type: number
              description: NTP offset threshold
            reportIntervalInSec:
              type: number
              description: Warning Report Interval in seconds.
          required:
          - threshold
        - type: boolean
          description: NTP sync warning alerts
          default: true
      temperature:
        type: object
        description: Reader temperature warning limits
        properties:
          ambient:
            type: number
            description: Ambient temperature limit
            default: 75
          pa:
            type: number
            description: PA temperature limit
            default: 105
        required:
        - ambient
        - pa
      database:
        type: boolean
        default: true
        description: Radio Database warnings
      radio_api:
        type: boolean
        default: true
        description: NGE warnings
      radio_control:
        type: boolean
        default: true
        description: Radio Control warnings
      reader_gateway:
        type: boolean
        default: true
        description: Reader Gateway Errors
  heartbeat:
    type: object
    description: Asynchronous Heartbeat Events
    properties:
      fields:
        type: object
        description: heartbeat fields
        properties:
          radio_control:
            type: array
            description: Radio Control related heartbeat events
            items:
              type: string
              enum:
              - ANTENNAS
              - RADIO_ACTIVITY
              - RADIO_CONNECTION
              - CPU
              - RAM
              - UPTIME
              - NUM_ERRORS
              - NUM_WARNINGS
              - NUM_TAG_READS
              - NUM_TAG_READS_PER_ANTENNA
              - NUM_DATA_MESSAGES_TXED
              - NUM_RADIO_PACKETS_RXED
          reader_gateway:
            type: array
            items:
              type: string
              enum:
              - NUM_DATA_MESSAGES_RXED
              - NUM_DATA_MESSAGES_TXED
              - NUM_DATA_MESSAGES_RETAINED
              - NUM_DATA_MESSAGES_DROPPED
              - NUM_MANAGEMENT_EVENTS_TXED
              - CPU
              - RAM
              - UPTIME
              - NUM_ERRORS
              - NUM_WARNINGS
          system:
            type: array
            items:
              type: string
              enum:
              - CPU
              - FLASH
              - NTP
              - RAM
              - SYSTEMTIME
              - TEMPERATURE
              - UPTIME
              - HOSTNAME
              - MACADDRESS
          userapps:
            type: array
            items:
              type: string
              enum:
              - STATUS
              - CPU
              - RAM
              - UPTIME
              - NUM_DATA_MESSAGES_RXED
              - NUM_DATA_MESSAGES_TXED
              - INCOMING_DATA_BUFFER_PERCENTAGE_REMAINING
              - OUTGOING_DATA_BUFFER_PERCENTAGE_REMAINING
          userDefined:
            type: object
            description: Custom user defined field
      interval:
        type: number
        description: heartbeat report interval in seconds
        default: 60
    required:
    - fields
    - interval
  gpiEvents:
    type: boolean
    description: GPI Events
    default: true
  userappEvents:
    type: boolean
    default: true
    description: Asynchronous events from user applications
