title: GPIO-LED configuration
type: object
description: 'GPIO-LED module configuration


  Configure GPO and LED behaviour based on Events generated


  Supported Events:

  1. GPI_1_L: event raised when GPI 1 changed from HIGH to LOW

  2. GPI_1_H: event raised when GPI 1 changed from LOW to HIGH

  3. GPI_2_L: event raised when GPI 2 changed from HIGH to LOW

  4. GPI_2_H: event raised when GPI 2 changed from LOW to HIGH

  5. CLOUD_DISCONNECT: event raised when reader is disconnected from cloud

  6. CLOUD_CONNECT: event raised when reader is connected to cloud

  7. TAG_READ: event raised when a tag is read

  8. RADIO_START: event raised when inventory operation started using START API

  9. RADIO_STOP: event raised when inventory operation stopped using STOP API'
properties:
  GPODefaults:
    type: object
    description: GPO default configurations
    properties:
      '1':
        type: string
        enum:
        - HIGH
        - LOW
        description: set default state for GPO pin 1
      '2':
        type: string
        enum:
        - LOW
        - HIGH
        description: set default state for GPO pin 2
      '3':
        type: string
        enum:
        - HIGH
        - LOW
        description: set default state for GPO pin 3
      '4':
        type: string
        enum:
        - HIGH
        - LOW
        description: set default state for GPO pin 4
  LEDDefaults:
    type: object
    description: LED default configurations
    properties:
      '1':
        type: string
        enum:
        - GREEN
        - RED
        - AMBER
        description: set default color for LED 2
      '2':
        type: string
        enum:
        - GREEN
        - RED
        - AMBER
        description: set default color for LED 3
      '3':
        type: string
        enum:
        - RED
        - GREEN
        - AMBER
        description: set default color for LED 4
  GPI_1_H:
    $ref: ../common/gpoledAction.v1.yaml
  GPI_1_L:
    $ref: ../common/gpoledAction.v1.yaml
  GPI_2_H:
    $ref: ../common/gpoledAction.v1.yaml
  GPI_2_L:
    $ref: ../common/gpoledAction.v1.yaml
  CLOUD_DISCONNECT:
    $ref: ../common/gpoledAction.v1.yaml
  CLOUD_CONNECT:
    $ref: ../common/gpoledAction.v1.yaml
  TAG_READ:
    $ref: ../common/gpoledAction.v1.yaml
  RADIO_START:
    $ref: ../common/gpoledAction.v1.yaml
  RADIO_STOP:
    $ref: ../common/gpoledAction.v1.yaml
